name: AppSec Israel 2023

on: push

jobs:
  appsecil:
    runs-on: ubuntu-latest
    name: Hello world!
    steps:
      - run: |
          echo "hellow world!"
          uname -a
          env
          set
  zapscan:
    runs-on: ubuntu-latest
    name: zap scan (another vm)
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'https://juice-shop.herokuapp.com/'
