name: AppSec Israel 2023

on: push

jobs:
  appsecil:
    runs-on: ubuntu-latest
    name: Hello world!
    steps:
      - run: |
          echo "hellow world!"
          uname -a
          env
          set
